export const pastStudents = [
  {
    name: "Dr. Argha Sarkar",
    status: "Doctoral Fellow",
    researchTitle: "Methane Sensing Platform Using ZnO and Graphene Based Sensing Layers through Structural Modification",
    yearJoining: 2016,
    yearComplete: 2018,
    status: "Completed",
  },
  {
    name: "Dr. Achyuth Sarkar",
    status: "Doctoral Fellow",
    researchTitle: "To Study and Analysis of Modified Aggressive Packet Combining (APC) Scheme with Consideration of Physical Signals and Voltage Division Multiplexing",
    yearJoining: 2016,
    status: "Completed",
  },
  {
    name: "Dr. Sanjit Ningthoujam",
    status: "Doctoral Fellow",
    researchTitle: "The Performance of multipath ARQ protocols to achieve higher throughput in Wireless Networks and Molecular Communication",
    yearJoining: 2016,
    yearComplete: 2020,
    status: "Completed",
  },
  {
    name: "Dr. Madhusudan Maiti",
    status: "Doctoral Fellow",
    researchTitle: "Design of Power Efficient CDR Circuit Constituents for Serial Data Communication",
    yearJoining: 2016,
    yearComplete: 2020,
    status: "Completed",
  },
  {
    name: "Dr. Ashish Singh Parihar",
    status: "Doctoral Fellow",
    email: "ashishparihar.cs@gmail.com",
    researchTitle: "DESIGN AND IMPLEMENTATION OF NOVEL DME ALGORITHMS IN FANET AND THEIR INTEGRATION USING ML TECHNIQUES",
    yearJoining: 2020,
    yearComplete: 2023,
    currentPlacement: "Assistant Professor (Senior Grade)",
    currentAddress: "Jaypee Institute of Information Technology (JIIT), Noida",
    status: "Completed",
    avatar: "https://www.nitap.ac.in/storage/groups/11-Ashish%20Singh%20Parihar-.jpg",
  },
  {
    name: "Dr. Mayuri Kundu",
    status: "Doctoral Fellow",
    researchTitle: "Advanced ARQ technique / Channels",
    yearJoining: 2016,
    yearComplete: 2020,
    status: "Completed",
  },
  {
    name: "Sanjit Ningthoujam",
    status: "M.Tech",
    researchTitle: "Investigation of Packet Combining and Aggressive Packet Combining Schemes to get Higher Throughput and wide Flexibility",
    yearJoining: 2013,
    yearComplete: 2015,
    status: "Completed",
  },
  {
    name: "Rohit Kumar",
    status: "M.Tech",
    researchTitle: "Analysis of throughput and mean energy consumption of Multi hopped Aggressive Packet Combining Scheme",
    yearJoining: 2014,
    yearComplete: 2016,
    status: "Completed",
  },
  {
    name: "Avinash Maurya",
    status: "M.Tech",
    researchTitle: "Lightweight IoT Protocol Realizing Smart IT & Communication",
    yearJoining: 2015,
    yearComplete: 2017,
    status: "Completed",
  },
  {
    name: "Priyanka Bardalai",
    status: "M.Tech",
    researchTitle: "Vertex Cover based DDoS Detection and Mitigation Scheme using SDN approach",
    yearJoining: 2016,
    yearComplete: 2018,
    status: "Completed",
  },
  {
    name: "Umang",
    status: "M.Tech",
    researchTitle: "Design a new algorithm of Distributed Mutual Exclusion and Implementation in Machine Learning",
    yearJoining: 2016,
    yearComplete: 2018,
    status: "Completed",
  },
  {
    name: "Ashish Singh Parihar",
    status: "M.Tech",
    researchTitle: "Index Based Approach in Hadoop Ecosystem for Performance Improvement",
    yearJoining: 2017,
    yearComplete: 2019,
    currentAddress: "Assistant Professor (Grade-II), Jaypee Institute of Information Technology (JIIT), Noida (Sector 62), Uttar Pradesh, India",
    status: "Completed",
    avatar: "https://www.nitap.ac.in/storage/groups/11-Ashish%20Singh%20Parihar-.jpg",
  },
];

export const currentStudents = [
  {
    name: "Mr. Ganesh Kumar Mahato",
    status: "Doctoral Fellow",
    email: "ganesh.phd20@nitap.ac.in",
    researchTitle: "Cryptography",
    yearJoining: 2020,
    supervisor: "",
    coSupervisor: "",
    status: "Current",
    avatar: "https://www.nitap.ac.in/storage/groups/26-Mr.%20Ganesh%20Kumar%20Mahato-.jpg",
  },
  {
    name: "Mr. Anil Ram",
    status: "Doctoral Fellow",
    email: "anil.phd20@nitap.ac.in",
    researchTitle: "SDN",
    yearJoining: 2020,
    supervisor: "",
    coSupervisor: "",
    status: "Current",
    avatar: "https://www.nitap.ac.in/storage/groups/27-Mr.%20Anil%20Ram-jpeg",
  },
  {
    name: "Ms. Sonali Mondal",
    status: "Doctoral Fellow",
    email: "",
    researchTitle: "Networking",
    yearJoining: 2021,
    supervisor: "",
    coSupervisor: "",
    status: "Current",
    avatar: "https://www.nitap.ac.in/storage/groups/575-Ms.%20Sonali%20Mondal-jpeg",
  },
  {
    name: "Ms. Shalini Dhiman",
    status: "Doctoral Fellow",
    email: "",
    researchTitle: "Networking",
    yearJoining: 2022,
    supervisor: "",
    coSupervisor: "",
    status: "Current",
    avatar: "https://www.nitap.ac.in/storage/groups/576-Shalini%20Dhiman-.jpg",
  },
];

