/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9kUaf7RG0ZW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Research() {
  return (<>
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">Research Details</h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Explore the latest research in Information Security, Cryptography, and Wireless Sensor Network.
              </p>
            </div>
          </div>
          <img
            alt="Hero"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
            height="550"
            src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/ec226aab-64a4-4d93-8d69-a9985d4de5f2/original=true/AF587278F52795D9675270CAE6D2E8662C49546C3CBAC52FF22F5370CFCAAA0A.jpeg"
            width="550" />
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div
          className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Cryptography</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Explore the latest research in Cryptography, including Network Security, IoT, and IoT & Embedded
                Systems.
              </p>
            </div>
            <ul className="grid gap-6">
              <li>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Network Security</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Secure communication and data protection in networks.
                  </p>
                </div>
              </li>
              <li>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">IoT</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Cryptographic techniques for the Internet of Things.
                  </p>
                </div>
              </li>
              <li>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">IoT & Embedded Systems</h3>
                  <p className="text-gray-500 dark:text-gray-400">Cryptography for IoT and embedded devices.</p>
                </div>
              </li>
            </ul>
          </div>
          <img
            alt="Cryptography"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="310"
            src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/4ff1fb3b-f917-4828-876f-0c1384657c1f/width=700/photo_2024-05-02%2001.17.08.jpeg"
            width="550" />
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div
          className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
          <img
            alt="Big Data"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="310"
            src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/7cf0eec2-073c-46eb-ab2b-870aa771cbd9/width=700/photo_2024-05-02%2001.16.54.jpeg"
            width="550" />
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Big Data</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Explore the latest research in Big Data, including Big Data & Hadoop.
              </p>
            </div>
            <ul className="grid gap-6">
              <li>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Big Data & Hadoop</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Leveraging Hadoop for large-scale data processing and analysis.
                  </p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div
          className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Blockchain</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Explore the latest research in Blockchain technology.
              </p>
            </div>
            <ul className="grid gap-6">
              <li>
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Blockchain</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Distributed ledger technology and its applications.
                  </p>
                </div>
              </li>
            </ul>
          </div>
          <img
            alt="Blockchain"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="310"
            src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/d2acfc27-99ec-4626-89e8-27b186ae4baf/width=700/photo_2024-05-02%2001.17.12.jpeg"
            width="550" />
        </div>
      </div>
    </section>
  </>);
}
