/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9kUaf7RG0ZW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Research() {
  return (<>
<section className="w-full py-12 md:py-24 lg:py-32">
  <div className="container px-4 md:px-6">
    <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
      <div className="flex flex-col justify-center space-y-4">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">Research Details</h1>
          <p className="max-w-[600px] text-gray-500 md:text-l dark:text-gray-400">
            Swarnendu Kumar Chakraborty is working as an Associate Professor in the department of Computer Science and Engineering at National Institute of Technology (NIT), Arunachal Pradesh, Govt. of India. He has more than twelve years of teaching experience. His research areas are distributed systems, advanced error control, cryptography and Information Security. He is the author of more than 30 peer-reviewed publications in reputed journals.
          </p>
        </div>
      </div>
      <img
        alt="Hero"
        className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
        height="550"
        src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/ec226aab-64a4-4d93-8d69-a9985d4de5f2/original=true/AF587278F52795D9675270CAE6D2E8662C49546C3CBAC52FF22F5370CFCAAA0A.jpeg"
        width="550"
      />
    </div>
  </div>
</section>
<section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
  <div className="container px-4 md:px-6">
    <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
      <img
        alt="Distributed Systems"
        className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
        height="310"
        src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/7cf0eec2-073c-46eb-ab2b-870aa771cbd9/width=700/photo_2024-05-02%2001.16.54.jpeg"
        width="550"
      />
      <div className="flex flex-col justify-center space-y-4">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Distributed Systems</h2>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Explore the latest research in Distributed Systems.
          </p>
        </div>
        <ul className="grid gap-6">
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">Distributed Systems</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Study of distributed systems architecture and algorithms.
              </p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
  <div className="container px-4 md:px-6">
    <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
      <div className="flex flex-col justify-center space-y-4">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Advanced Error Control</h2>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Explore the latest research in Advanced Error Control.
          </p>
        </div>
        <ul className="grid gap-6">
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">Advanced Error Control</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Techniques for error detection and correction in data transmission.
              </p>
            </div>
          </li>
        </ul>
      </div>
      <img
        alt="Advanced Error Control"
        className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
        height="310"
        src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/7cf0eec2-073c-46eb-ab2b-870aa771cbd9/width=700/photo_2024-05-02%2001.16.54.jpeg"
        width="550"
      />
    </div>
  </div>
</section>
<section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
  <div className="container px-4 md:px-6">
    <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
      <img
        alt="Cryptography"
        className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
        height="310"
        src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/4ff1fb3b-f917-4828-876f-0c1384657c1f/width=700/photo_2024-05-02%2001.17.08.jpeg"
        width="550"
      />
      <div className="flex flex-col justify-center space-y-4">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Cryptography</h2>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Explore the latest research in Cryptography, including Network Security, IoT, and IoT & Embedded Systems.
          </p>
        </div>
        <ul className="grid gap-6">
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">Network Security</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Secure communication and data protection in networks.
              </p>
            </div>
          </li>
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">IoT</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Cryptographic techniques for the Internet of Things.
              </p>
            </div>
          </li>
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">IoT & Embedded Systems</h3>
              <p className="text-gray-500 dark:text-gray-400">Cryptography for IoT and embedded devices.</p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
  <div className="container px-4 md:px-6">
    <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
      <div className="flex flex-col justify-center space-y-4">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Information Security</h2>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Explore the latest research in Information Security.
          </p>
        </div>
        <ul className="grid gap-6">
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">Cybersecurity</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Protection of digital information and systems from unauthorized access and attacks.
              </p>
            </div>
          </li>
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">Data Privacy</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Ensuring the confidentiality and integrity of sensitive information.
              </p>
            </div>
          </li>
          <li>
            <div className="grid gap-1">
              <h3 className="text-xl font-bold">Cyber Threat Intelligence</h3>
              <p className="text-gray-500 dark:text-gray-400">Collecting and analyzing data to identify cybersecurity threats.</p>
            </div>
          </li>
        </ul>
      </div>
      <img
        alt="Information Security"
        className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
        height="310"
        src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/4ff1fb3b-f917-4828-876f-0c1384657c1f/width=700/photo_2024-05-02%2001.17.08.jpeg"
        width="550"
      />
    </div>
  </div>
</section>





  </>);
}
