/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ioBs89DEH8S
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { currentStudents, pastStudents } from "@/app/consts/students";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function Students() {
  return (<>
    <section className="py-12 md:py-20 bg-transparent">
      <div className="container mx-auto px-4 md:px-6">
        <h2 className="mb-8 text-3xl font-bold md:text-4xl">Current Students</h2>
        <div
          className=" flex flex-wrap gap-10 justify-center">
          
          {
            currentStudents.map((student, i) => (
              <StudentCard key={i} student={student} />
            ))
          }




          
        </div>
      </div>
    </section><section className="py-12 md:py-20">
      <div className="container mx-auto px-4 md:px-6">
        <h2 className="mb-8 text-3xl font-bold md:text-4xl">Past Students</h2>
        <div
          className=" flex flex-wrap gap-10 justify-center">
          
          {
            pastStudents.map((student, i) => (
              <StudentCard key={i} student={student} />
              
            ))
          }




          
        </div>
      </div>
    </section>
    
  </>);
}


export const StudentCard = ({student}) => {
  return <div className="flex flex-col 
  hover:border hover:border-gray-200 hover:shadow-lg hover:shadow-gray-900
 
   cursor-pointer w-[30%] items-center rounded-lg bg-white p-6 shadow-md dark:bg-gray-950">
  <Avatar className="mb-4 h-20 w-20">
    <AvatarImage alt={student.name} src={student.avatar} className=" object-contain "/>
    <AvatarFallback>{student.name[0]}</AvatarFallback>
  </Avatar>
  <h3 className="mb-2 text-lg font-semibold">{student.name}</h3>
  <p className="text-sm text-gray-500 dark:text-gray-400">Joined: {student.yearJoining}</p>
  <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">{student.email}</p>
  <p className="mb-2 text-center"> <span className=" text-red-100">Research</span> <br /> {student.researchTitle}</p>
  <p className="mb-2  text-green-400">{student.status}</p>
</div>
}