/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/j2KgFIczLyq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, Card } from "@/components/ui/card"


export function Workshop() {
  return (
    <main className="w-full max-w-4xl mx-auto px-4 py-12 md:py-16 lg:py-20">
      <div className="space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">Workshop/Conference Attended</h1>
          <p className="mt-4 max-w-2xl mx-auto text-gray-500 dark:text-gray-400">
            Highlighting participation in significant blockchain technology events.
          </p>
        </div>
        <div className="grid gap-6 sm:grid-cols-2">
          <Card className="card p-2">
            <CardHeader>
              <CardTitle>Blockchain Technology Workshop</CardTitle>
              <CardDescription>
                <div className="space-y-2">
                  <p>
                    <span className="font-medium">Institute:</span> National Institute of Technology Arunachal Pradesh
                  </p>
                  <p>
                    <span className="font-medium">Date:</span> 10th-14th February, 2020
                  </p>
                  <p>
                    <span className="font-medium">Type:</span> National
                  </p>
                  <p>
                    <span className="font-medium">Place:</span> Yupia, Papum Pare, Arunachal Pradesh
                  </p>
                  <p>
                    <span className="font-medium">Organised by:</span> Dr. Rajat Subhra Goswami
                  </p>
                </div>
              </CardDescription>
            </CardHeader>
          </Card>
          <Card className="card p-2">
            <CardHeader>
              <CardTitle>Blockchain Technology Conference</CardTitle>
              <CardDescription>
                <div className="space-y-2">
                  <p>
                    <span className="font-medium">Institute:</span> National Institute of Technology Arunachal Pradesh
                  </p>
                  <p>
                    <span className="font-medium">Date:</span> 14th-18th December, 2020
                  </p>
                  <p>
                    <span className="font-medium">Type:</span> National
                  </p>
                  <p>
                    <span className="font-medium">Place:</span> Yupia, Arunachal Pradesh
                  </p>
                  <p>
                    <span className="font-medium">Organised by:</span> Dr. Rajat Subhra Goswami
                  </p>
                </div>
              </CardDescription>
            </CardHeader>
          </Card>
        </div>
      </div>
    </main>
  );
}

